account_register:
   pattern:  /register
   defaults: { _controller: EverFailRegistrationBundle:Registration:register }

account_create:
   pattern:  /register/create
   defaults: { _controller: EverFailRegistrationBundle:Submission:submission }

confirm:
  pattern: /confirm
  defaults: { _controller: EverFailRegistrationBundle:Confirm:confirm }

profile:
   pattern: /profile
   defaults: { _controller: EverFailMainBundle:Default:index }

welcome:
   pattern: /home
   defaults: { _controller: EverFailMainBundle:Default:index }

account_login:
   pattern:  /login
   defaults: { _controller: EverFailRegistrationBundle:Login:login }
   
account_logout:
   pattern:  /logout
   defaults: { _controller: EverFailRegistrationBundle:Login:logout }
