ever_fail_main:
    resource: "@EverFailMainBundle/Resources/config/routing.yml"
    prefix:   /

ever_fail_reg:
    resource: "@EverFailRegistrationBundle/Resources/config/routing.yml"
    prefix:   /

