car:
    pattern:  /
    defaults: { _controller: "EverFailMainBundle:Car:index" }

car_show:
    pattern:  /{id}/show
    defaults: { _controller: "EverFailMainBundle:Car:show" }

car_new:
    pattern:  /{CustId}/new
    defaults: { _controller: "EverFailMainBundle:Car:new" }

car_create:
    pattern:  /{CustId}/create
    defaults: { _controller: "EverFailMainBundle:Car:create" }
    requirements: { _method: post }

car_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "EverFailMainBundle:Car:edit" }

car_update:
    pattern:  /{id}/update
    defaults: { _controller: "EverFailMainBundle:Car:update" }
    requirements: { _method: post|put }

car_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "EverFailMainBundle:Car:delete" }
    requirements: { _method: post|delete }

wizard_car_show:
        pattern: /{CustId}/{CarId}/carShow
        defaults: { _controller: "EverFailMainBundle:InitialRegistration:showCar" }