EverFail\UserAuthBundle\Entity\Users:
    type: entity
    table: null
    repositoryClass: EverFail\UserAuthBundle\Entity\UsersRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: '20'
            column: Username
        password:
            type: string
            length: 255
            column: Password
        role:
            type: string
            length: '20'
            column: Role
        email:
            type: string
            length: '40'
        status:
            type: string
            length: '15'
            column: Status
    lifecycleCallbacks: {  }
