parameters:
#    ever_fail_wizard.example.class: EverFail\WizardBundle\Example

services:
#    ever_fail_wizard.example:
#        class: %ever_fail_wizard.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
