ever_fail_user_auth_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: EverFailUserAuthBundle:Default:index }  
EverFailUserAuthBundle_users:
        resource: "@EverFailUserAuthBundle/Resources/config/routing/users.yml"
        prefix:   /users

