parameters:
#    ever_fail_user_auth.example.class: EverFail\UserAuthBundle\Example

services:
#    ever_fail_user_auth.example:
#        class: %ever_fail_user_auth.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
